In [3]:
import numpy as np
import cv2

In [4]:
img = cv2.imread(r"E:\MTN-302\mte 16_1.jpg",1) #rgb
img2 = cv2.imread(r"E:\MTN-302\mte 16_1.jpg",0) #greyscale
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
cv2.imshow('image',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
edges = cv2.Canny(img,100,200)
cv2.imshow('Edges', edges)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
import cv2
import numpy as np

img = cv2.imread(r"E:\MTN-302\mte 16_1.jpg")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


edges = cv2.Canny(gray,100,200,apertureSize = 3)
cv2.imshow('edges',edges)
cv2.waitKey(0)

minLineLength = 2
maxLineGap = 35
lines = cv2.HoughLinesP(edges,1,np.pi/180,500,minLineLength,maxLineGap)
for x in range(0, len(lines)):
    for x1,y1,x2,y2 in lines[x]:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow('hough',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

TypeError: object of type 'NoneType' has no len()

In [7]:
lines

array([[[ 21, 136, 865, 136]],

       [[ 23, 227, 846, 227]],

       [[ 21,  91, 844,  91]],

       [[605, 177, 849, 177]],

       [[ 21, 223, 847, 223]],

       [[ 22, 132, 865, 132]],

       [[ 23, 182, 851, 182]],

       [[ 21,  87, 844,  87]],

       [[ 23, 268, 267, 268]],

       [[ 22, 272, 267, 272]],

       [[171, 177, 224, 177]],

       [[ 23, 177,  72, 177]]])

In [9]:
lines[1][0]


array([ 23, 227, 846, 227])

In [10]:
lines.shape

(12L, 1L, 4L)

In [11]:
lines1 = np.transpose(lines)
lines1

array([[[ 21,  23,  21, 605,  21,  22,  23,  21,  23,  22, 171,  23]],

       [[136, 227,  91, 177, 223, 132, 182,  87, 268, 272, 177, 177]],

       [[865, 846, 844, 849, 847, 865, 851, 844, 267, 267, 224,  72]],

       [[136, 227,  91, 177, 223, 132, 182,  87, 268, 272, 177, 177]]])

In [12]:
list_x1 = lines1[0][0]
list_y1 = lines1[1][0]
list_x2 = lines1[2][0]
list_y2 = lines1[3][0] 

In [13]:
list_x2

array([865, 846, 844, 849, 847, 865, 851, 844, 267, 267, 224,  72])

In [14]:
list_x2.shape

(12L,)

In [15]:
lines1.shape

(4L, 1L, 12L)

In [16]:
list_x1

array([ 21,  23,  21, 605,  21,  22,  23,  21,  23,  22, 171,  23])

In [17]:
x1= sorted(list_x1)
x2= sorted(list_x2)
y1= sorted(list_y1)
y2= sorted(list_y2)

In [18]:
y2

[87, 91, 132, 136, 177, 177, 177, 182, 223, 227, 268, 272]

In [19]:
'''l_x1= lines1[0]
l_x1
l_x1[0].shape
len(l_x1[0])
sorted_x1 = []
sorted_x1.append(sorted(l_x1[0]))
sorted(l_x1[0])'''

'l_x1= lines1[0]\nl_x1\nl_x1[0].shape\nlen(l_x1[0])\nsorted_x1 = []\nsorted_x1.append(sorted(l_x1[0]))\nsorted(l_x1[0])'

In [17]:
'''cropped = []
for a,b,c in zip(y1,x1,x2):
    cropped.append(img[a:a+40 , b:b+c])'''

'cropped = []\nfor a,b,c in zip(y1,x1,x2):\n    cropped.append(img[a:a+40 , b:b+c])'

In [21]:
cropped = []
for a,b,c in zip(list_y1,list_x1, list_x2):
    cropped.append(img[a-40:a , b:b+c])      #img[y:y+height, x:x+width]

In [22]:
cropped

[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[154, 154, 154],
         [  0, 255,   0],
         [  0, 255,   0],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[141, 141, 141],
         [ 21,  21,  21],
         [  0,   0,   0],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[  0, 255,   0],
         [  0, 255,   0],
         [  0, 255,   0],
         ...,
         [255, 255, 255],
  

In [23]:
for crop in cropped:
    cv2.imshow("cropped", crop)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [21]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
cropped2 = img[91:132 , 21:865]  #img[y:y+height, x:x+width]
cropped2
cv2.imshow("cropped2", cropped2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
'''from PIL import Image
from pytesseract import image_to_string
print(image_to_string(img,config='-psm 6'))'''

"from PIL import Image\nfrom pytesseract import image_to_string\nprint(image_to_string(img,config='-psm 6'))"

In [34]:
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 127, 255, 0)
im2, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

In [41]:
im= cv2.drawContours(img, contours, -1, (0,255,0), 3)


In [42]:
cv2.imshow('im', im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
im


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [27]:
img = cv2.imread(r"C:\Users\welcome\Desktop\underlining.png")
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cropped2 = img[94:132 , 21:865]  #img[y:y+height, x:x+width]
cropped2
cv2.imshow("cropped2", cropped2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
imgray = cv2.cvtColor(cropped2, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 127, 255, 0)
im2, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

im = cv2.drawContours(cropped2, contours, -1, (0,255,0), 3)

cv2.imshow('im', im)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [29]:
print im.shape
im

(38L, 844L, 3L)


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [30]:
cropped3 = img[94:132 , 21:865]  #img[y:y+height, x:x+width]

cv2.imshow("cropped2", cropped3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
print np.transpose(im).shape
np.transpose(im)

(3L, 844L, 38L)


array([[[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]]], dtype=uint8)

In [32]:
[y, x] = np.where(im[0], im[1])

ValueError: either both or neither of x and y should be given

In [ ]:
[y, x]

In [ ]:
# Import the cv2 library
import cv2
# Read the image you want connected components of
src = cv2.imread(r"C:\Users\welcome\Desktop\underlining.png",0)
# Threshold it so it becomes binary
ret, thresh = cv2.threshold(src,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
# You need to choose 4 or 8 for connectivity type
connectivity = 4  
# Perform the operation
output = cv2.connectedComponentsWithStats(thresh, connectivity, cv2.CV_32S)
# Get the results
# The first cell is the number of labels
num_labels = output[0]
# The second cell is the label matrix
labels = output[1]
# The third cell is the stat matrix
stats = output[2]
# The fourth cell is the centroid matrix
centroids = output[3]

In [ ]:
##########################################################################################
####
####             Connected-Component labeling Two-Pass algorithm  (8-connectivity)
#### 
##########################################################################################
####
####             Cluster elevation matrix - iso-elevation regions 
####            
##########################################################################################

import numpy as np
## based on http://en.wikipedia.org/wiki/Connected-component_labeling

## based on
## Connected Component Labeling Algorithms for Gray-Scale Images 
## and Evaluation of Performance using Digital Mammograms, R. Dharshana Yapa
## and  K. Harada

#######################################################################################################

class disjointSet:

    def __init__(self, n):
        self.parent = [0]*n
        self.rank = [0]*n

    def makeSet(self,x):
        self.parent[x] = x
        self.rank[x] = 0

    def union(self,x,y):
        xRoot = self.find(x)
        yRoot = self.find(y)
        
        if(xRoot == yRoot):
            return

        if(self.rank[xRoot] < self.rank[yRoot]):
            self.parent[xRoot] = yRoot
        elif(self.rank[xRoot] > self.rank[yRoot]):
            self.parent[yRoot] = xRoot
        else:
            self.parent[yRoot] = xRoot
            self.rank[xRoot] += 1
            
    def find(self, x):
        if (self.parent[x] != x):
            self.parent[x] = self.find(self.parent[x])
        return self.parent[x]

class disjointRegions(disjointSet):

    def __init__(self, n):
        self.parent = [0]*n
        self.rank = [0]*n
        self.cell = [0]*n # top left hand corner cell for regions
        self.utils = 0 # effective number of new created label 
        self.neighbors = [[]]*n

    def makeSet(self,x,i,j):
        self.parent[x] = x
        self.rank[x] = 0
        self.cell[x] = (i,j)
        self.utils += 1

    def union(self,x,y):
        xRoot,xCell = self.find(x)
        yRoot,yCell = self.find(y)
        if(xRoot == yRoot):
            return

        if(self.rank[xRoot] < self.rank[yRoot]):
            self.parent[xRoot]  = yRoot 
        elif(self.rank[xRoot] > self.rank[yRoot]):
            self.parent[yRoot]  = xRoot 
        else:
            self.parent[yRoot] = xRoot
            self.rank[xRoot] += 1

    def find(self, x):
        if (self.parent[x] != x):
            self.parent[x] = self.find(self.parent[x])[0]

        return self.parent[x], self.cell[self.parent[x]]  # return representative for region: label, cell

    def topDown(self,x):
        '''
        Return all labels whose parent is x's parent
        '''
        tDlabel  = []
        
        for i in range(self.utils):
            #print ' i ' + str(i) + ' self.find(i)[0] ' + str(self.find(i)[0]) + ' x ' + str(x) + ' ' + str(self.find(x)[0])

            if(self.find(i)[0] == self.find(x)[0]):
                
                tDlabel.append(i)
                 
        return tDlabel

##########################################################################################################

class CC_lab:

    def __init__(self,mat):
        self.labels = []
        self.forest = 0
        self.mat = mat

        
            
    def connectedComponentLabel(self,n_clusters=0):
            '''
            Label regions belonging to the same color level
            Algorithm uses disjoint-set data structure (equivalence table) and
            it is based on
            A Run-Based Two-Scan Labeling Algorithm, L. H, Y. Chao, K. Suzuki, IEEE
            '''
            N, M = len(self.mat), len(self.mat[0])
                 
            if(n_clusters==0):
                n_clusters = N * M

            self.labels = sameDimZeroMatrix(self.mat) # build label matrix with appropriate dimensions
            label = 0 # next label to be assigned

            self.forest = disjointRegions(n_clusters) # forest to record equivalences
            
            for i in range(N):
                
                for j in range(M):

                    neighbors = self.connectedNeighbors(i,j) # neighbors with same value
                    
                    #print 'neighbors ' + str(neighbors) +' for pixel at ' + str(i) + ', '+ str(j)
                    
                    if (neighbors == [[],[],[],[]]): # no neighbors at all
                        #print 'case no neighbors at all'
                        self.labels[i][j] = label # new label
                        self.forest.makeSet(label,i,j)
                        
                        label += 1
                            
                    else:
                         
                        ##find minimum neighbor
                        lab = [] # labels for neighbor pixels that are available

                        for pix in range(4):
                            if(neighbors[pix] != []): # some neighbor in this direction
                                x,y = neighbors[pix][0][0], neighbors[pix][0][1]
                                lab.append(self.labels[x][y])
                                
                        if(len(lab) > 1): # at least two neighbors from north, west, north-west, north-east
                            #print 'more than 1 neighbors'
                            self.labels[i][j] = min(lab)
                            
                            for l in range(len(lab)-1):
                                
                                self.forest.union(lab[l], lab[l+1])  # union labels, maybe they are different      
                            
                        else:
                            #print 'only 1 neighbors'
                            if(neighbors[0] != []):
                                #print 'adopted west'
                                self.labels[i][j] = self.labels[neighbors[0][0][0]][neighbors[0][0][1]]
     
                            elif(neighbors[1] != []): # some north neighbor only
                                #print 'adopted north' 
                                self.labels[i][j] = self.labels[neighbors[1][0][0]][neighbors[1][0][1]]

                            elif(neighbors[2] != []): # some north-west neighbor only
                                #print 'adopted north-west' 
                                self.labels[i][j] = self.labels[neighbors[2][0][0]][neighbors[2][0][1]]
              
                            elif(neighbors[3] != []): # some north-east neighbor only
                                #print 'adopted north-east' 
                                self.labels[i][j] = self.labels[neighbors[3][0][0]][neighbors[3][0][1]] 

                    if(neighbors[0] == [] and i > 0):
                        self.updateNeighbors(i,j,i-1,j) 

                    if(neighbors[1] == [] and j > 0):
                        self.updateNeighbors(i,j,i,j-1)

                    if(neighbors[2] == [] and i > 0 and j > 0):
                        self.updateNeighbors(i,j,i-1,j-1)

                    if(neighbors[3] == [] and i > 0 and j < M-1):
                        self.updateNeighbors(i,j,i-1,j+1)

            # second pass
            for i in range(N):

                for j in range(M):

                    self.labels[i][j] = self.forest.find(self.labels[i][j])[0]



    def updateNeighbors(self, i, j, k, l):
        '''
        Region labeled with label(i,j) and region labeled with label(k,l) are neighbor, update
        self.forest.neighbors twice
        '''
        self.forest.neighbors[self.labels[i][j]] = np.unique([x for x in self.forest.neighbors[self.labels[i][j]]] + [self.labels[k][l]])
        self.forest.neighbors[self.labels[k][l]] = np.unique([x for x in self.forest.neighbors[self.labels[k][l]]] + [self.labels[i][j]])


              
    def neighborRegions(self,labelij,mat):
        '''
        Return neighbor regions for the region with label labelij
        '''
        neighbors = []
        R,C = len(mat), len(mat[0])
 
        parentij = self.forest.find(labelij)[0] # representative for the region which the cell i,j belongs to
        areas = self.forest.topDown(parentij)  # list of areas in the region which the cell i,j belongs to

        for area in areas:
            
            neighboor_ = self.forest.neighbors[area]

            for k in range(len(neighboor_)):
                neighboor_label = self.forest.find(neighboor_[k])[0]
                if(neighboor_label != labelij):
                    neighbors.append(neighboor_label)
             
        return np.unique(neighbors)




    def labelToElevation(self, label_i):
        '''
        From label, retrieve elevation in matrix self.mat
        '''
        x,y = self.forest.cell[label_i]
        return self.mat[x][y]

        
        
    def connectedNeighbors(self,i, j): 
        '''
        Return coordinates for neighbors of pixel i, j that have same value
        as pixel i, j (8-connectivity)
        '''
        neighbors = []
        for z in range(4):
            neighbors.append([])

        N, M = len(self.mat), len(self.mat[0])
        
        if(i >= N or j >= M or i < 0 or j < 0): # exceed dimensions
            return []

        val = self.mat[i][j]
        
        if(i == 0 and j == 0): ## top left-hand corner, no neighbors
            return neighbors

        # i or j is not zero
        if(j > 0):
            
            if(val == self.mat[i][j-1]):
                neighbors[0].append((i, j-1)) ## west
  
        if(i > 0):
            
            if(val == self.mat[i-1][j]):
                neighbors[1].append((i-1, j)) ## north

        if(i > 0 and j > 0): 
            if(val == self.mat[i-1][j-1]):
                neighbors[2].append((i-1, j-1)) ## north-west
        
        if(i > 0 and j < M-1): 
            if(val == self.mat[i-1][j+1]):
                neighbors[3].append((i-1, j+1)) ## north-east
                
        return neighbors


    def matrixFromLabelsList(self, region_values, N, M):
        '''
        Input array region_values contains values for each region in self.labels.
        Returns the matrix with pixel i,j colored with the value for the region which this pixel belongs to.
        '''
        toPlot = []
    
        for i in range(N):
            tmp = []
            for j in range(M):
                tmp.append(region_values[self.forest.find(self.labels[i][j])[0]-1]) # watershed label for the region (i,j) belongs to
            toPlot.append([x for x in tmp])

        return toPlot 

     
def sameDimZeroMatrix(mat):
    '''
    Create matrix with same dimensions as mat with zeros
    '''
    zeros = []
    
    for i in range(len(mat)):
        tmp = []
        for j in range(len(mat[i])):
            tmp.append(0)
        zeros.append([x for x in tmp])
        
    return zeros

In [24]:
from PIL import Image
import pytesseract
from pytesseract import image_to_string

pytesseract.pytesseract.tesseract_cmd = 'C:/Program Files (x86)/Tesseract-OCR/tesseract'
print pytesseract.image_to_string(Image.open(r"C:\Users\welcome\Desktop\underrrrrrr.png"))

writers had no bold or italic styling. So the only way to empha-
